language: csharp
mono: none
dotnet: 2.0.0

os:
  - linux
  - osx

install:
- dotnet restore src/Microsoft.VisualStudio.Composition.sln

script:
- dotnet build src/Microsoft.VisualStudio.Composition/Microsoft.VisualStudio.Composition.csproj
- dotnet test -f netcoreapp1.0 --no-build --no-restore src/tests/Microsoft.VisualStudio.Composition.Tests/
- dotnet test -f netcoreapp2.0 --no-build --no-restore src/tests/Microsoft.VisualStudio.Composition.Tests/
